package com.heater.analysis;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

public final class ReadmePatcher {

    private static final Pattern MARKER_PATTERN = Pattern.compile(
            "<!-- SCALABILITY:BEGIN[^>]*-->.*?<!-- SCALABILITY:END -->",
            Pattern.DOTALL
    );

    private ReadmePatcher() {}

    public static void patch(Path readmePath, String scalabilityMarkdown) throws IOException {
        String readme = Files.readString(readmePath);
        if (!readme.contains("<!-- SCALABILITY:BEGIN")) {
            throw new IllegalStateException(
                    "README missing SCALABILITY markers at " + readmePath);
        }
        String replacement = "<!-- SCALABILITY:BEGIN — auto-generated by ./gradlew generateFigures; do not edit -->\n"
                + scalabilityMarkdown.trim()
                + "\n<!-- SCALABILITY:END -->";
        Matcher m = MARKER_PATTERN.matcher(readme);
        if (!m.find()) {
            throw new IllegalStateException("Could not match SCALABILITY marker block in README");
        }
        String updated = m.replaceFirst(Matcher.quoteReplacement(replacement));
        Files.writeString(readmePath, updated);
    }
}
