package com.heater.analysis;

import java.io.IOException;
import java.util.List;
import java.util.Locale;

public final class TemplateExplainer {

    private TemplateExplainer() {}

    public static String explain(ResultsSummary summary, String gpuProfilesPath) throws IOException {
        GpuProfile.GpuProfileRegistry registry = GpuProfile.load(gpuProfilesPath);
        ClimateAnalogies impact = ClimateAnalogies.loadDefault();
        StringBuilder sb = new StringBuilder();

        sb.append("## Scalability: GPUs, heat, and CO₂\n\n");
        sb.append("*Auto-generated by `./gradlew generateFigures`. Charts use **cars off the road** instead of tonnes — ")
                .append("see [impact analogies](config/impact_analogies.yaml).*\n\n");

        sb.append("### The takeaway\n\n");
        sb.append("- **More GPUs → more waste heat** — like more cars idling in a parking garage, all exhausting heat.\n");
        sb.append("- **More heat can pull more CO₂ from the air** — but only if capture equipment grows with the hall (bigger bucket).\n");
        sb.append("- **Newer NVIDIA chips run hotter each generation**, so the same hall with Blackwell or Rubin can do more climate work.\n\n");

        sb.append("### How many GPUs are we talking about?\n\n");
        sb.append(String.format(Locale.US,
                "Our **reference hall** has **%,d %s GPUs** and about **%.0f MW** of average waste heat "
                        + "(heat per chip × chip count).\n\n",
                registry.referenceGpuCount(),
                registry.referenceProfile().displayName(),
                registry.referenceProfile().avgWasteHeatMw(registry.referenceGpuCount())
        ));
        sb.append("**Is that realistic?** Yes for a serious U.S. AI buildout. xAI's Colossus cluster in Memphis uses "
                + "**four ~25,000-GPU compute halls** (100,000 H100s total) per the [ServeTheHome / Supermicro tour](https://www.servethehome.com/inside-100000-nvidia-gpu-xai-colossus-cluster-supermicro-helped-build-for-elon-musk/). "
                + "We model **one such hall**, not an entire campus.\n\n");
        sb.append("**Older note:** An earlier draft used ~37,000 GPUs (~50 MW). That was thermodynamically consistent but "
                + "**larger than documented single-hall deployments**. We recalibrated to **25,000 GPUs** (~34 MW on B200 liquid).\n\n");

        appendChartSection(sb, summary, impact, "gpu_count_ramp", "co2_vs_gpu_count.png",
                "Chart 1 — More GPUs (H100-class hall)",
                "More lunch trays → more leftover hot food → more composting.",
                "When the capture plant scales with the GPUs, removal grows steadily.");
        appendChartSection(sb, summary, impact, "gpu_generation", "co2_vs_gpu_generation.png",
                "Chart 2 — Same hall, newer chips",
                "Same kitchen, but each stove upgraded to a stronger burner.",
                "Hotter chips push more waste heat through the same number of GPUs.");
        appendChartSection(sb, summary, impact, "saturation", "co2_saturation_gpu.png",
                "Chart 3 — Fixed capture plant, more heat",
                "A fire hose filling a bucket that never gets bigger — water spills over.",
                "Past ~1× reference heat, the curve flattens: equipment is maxed out.");
        appendChartSection(sb, summary, impact, "multi_hall", "co2_multi_hall.png",
                "Chart 4 — Campus rollout (many halls)",
                "One school compost program copied to 10, then 100 schools.",
                "Each ~25k-GPU hall adds another chunk of cars-off-road impact.");
        appendGrossNetSection(sb, summary, impact);
        appendGpuTimelineSection(sb);

        sb.append("### What does removing CO₂ actually mean?\n\n");
        sb.append("A **tonne** is a metric ton (1,000 kg) — accurate for scientists but meaningless to most people. ")
                .append("Below we translate every headline number into **cars off U.S. roads for one year** ")
                .append(String.format(Locale.US, "(≈ %.1f tonnes CO₂ per car, EPA average).\n\n", impact.carTonnesPerYear()));

        sb.append("### Results — in cars, not just tonnes\n\n");
        sb.append("| Story | GPUs | Chip | Halls | Cars off the road / year | What that means |\n");
        sb.append("|-------|------|------|-------|--------------------------|-----------------|\n");
        appendStoryRow(sb, summary, impact, "gpu_count_ramp", 5000, "Startup lab");
        appendStoryRow(sb, summary, impact, "gpu_count_ramp", 25000, "One Colossus-style hall (H100)");
        appendStoryRow(sb, summary, impact, "gpu_generation", 25000, "One hall (B200 liquid)", "B200_LC");
        appendStoryRow(sb, summary, impact, "multi_hall", 10, "10-hall campus");
        appendForecastRow(sb, summary, impact, "2026", "Rubin forecast hall");

        appendWorthItSection(sb, summary, impact, registry);

        sb.append("\n### Four stories\n\n");
        appendStory(sb, summary, impact, "The lab (~5,000 GPUs)", "gpu_count_ramp", 5000);
        appendStory(sb, summary, impact, "The hall (~25,000 GPUs)", "gpu_generation", "B200_LC");
        appendStory(sb, summary, impact, "The campus (10 halls)", "multi_hall", 10);
        appendStory(sb, summary, impact, "The Rubin future", "forecast_timeline", "2026");

        sb.append("### Common questions (FAQ)\n\n");
        sb.append("**Does more AI automatically help the climate?** No. Heat must power capture — not just vent to the sky.\n\n");
        sb.append("**Why show cars instead of tonnes?** People grasp \"cars off the road\"; tonnes are abstract.\n\n");
        sb.append("**Are 25,000 GPUs in one hall real?** Yes — xAI Colossus documents ~25k per compute hall. A full campus is 4× that or more.\n\n");
        sb.append("**Why does electricity matter?** Heat pumps use grid power, which still emits CO₂ — that shrinks the net benefit.\n\n");
        sb.append("**Is this a full climate fix?** No. Even 100 halls is tiny vs ~36 billion tonnes global emissions/year.\n\n");
        sb.append("**Is ~8,000 cars worth it for 25,000 GPUs?** See [recovery from GPU operations](#is-it-worth-it--recovery-from-gpu-operations) — "
                + "the fair comparison is what fraction of the hall's **own** grid emissions DAC gives back.\n\n");

        sb.append("### Generated at: ").append(summary.generatedAt()).append("\n\n");
        sb.append("### Sources & disclaimers\n\n");
        sb.append("- **Hall size:** ServeTheHome / Supermicro xAI Colossus tour (~25k GPUs/hall).\n");
        sb.append("- **Car analogy:** U.S. EPA ~4.6 tonnes CO₂/year per average passenger vehicle.\n");
        sb.append("- **GPU heat:** NVIDIA datasheets + SemiAnalysis NVL72 rack power (~120 kW / 72 GPUs).\n");
        sb.append("- **Forecast chips (B300, Rubin):** Public GTC roadmaps — illustrative, not NVIDIA internal specs.\n");

        return sb.toString();
    }

    private static void appendChartSection(
            StringBuilder sb, ResultsSummary summary, ClimateAnalogies impact,
            String sweepId, String chartFile, String title, String analogy, String lesson
    ) {
        sb.append("### ").append(title).append("\n\n");
        sb.append("![").append(title).append("](docs/figures/").append(chartFile).append(")\n\n");
        sb.append("*").append(impact.chartSubtitle()).append("*\n\n");
        sb.append("**Analogy:** ").append(analogy).append("\n\n");
        sb.append("**Lesson:** ").append(lesson).append("\n\n");
        List<SweepPoint> pts = summary.bySweep(sweepId);
        if (!pts.isEmpty()) {
            SweepPoint highlight = pts.get(Math.min(pts.size() / 2, pts.size() - 1));
            sb.append("**Example from this sim:** ").append(highlight.label()).append(" → ");
            sb.append(impact.explainRemoval(highlight.annualizedNetTonnes())).append("\n\n");
        }
    }

    private static void appendGrossNetSection(StringBuilder sb, ResultsSummary summary, ClimateAnalogies impact) {
        sb.append("### Chart 5 — Gross vs. net (the electricity penalty)\n\n");
        sb.append("![Gross vs net](docs/figures/gross_vs_net_co2.png)\n\n");
        sb.append("*").append(impact.chartSubtitle()).append(" — two lines: before and after heat-pump electricity.*\n\n");
        sb.append("**Analogy:** Gross = cookies baked; net = cookies minus the eggs you had to buy at the store.\n\n");
        List<SweepPoint> pts = summary.bySweep("gpu_count_ramp");
        if (!pts.isEmpty()) {
            SweepPoint p = pts.get(pts.size() - 1);
            sb.append(String.format(Locale.US,
                    "At **%,d GPUs**: gross **%s** vs net **%s** per year. The gap is the CO₂ cost of running heat pumps.\n\n",
                    p.gpuCount(),
                    impact.formatCars(impact.carsFromAnnualTonnes(p.annualizedGrossTonnes())),
                    impact.formatCars(impact.carsFromAnnualTonnes(p.annualizedNetTonnes()))));
        }
    }

    private static void appendGpuTimelineSection(StringBuilder sb) {
        sb.append("### Chart 6 — GPU heat rises each generation\n\n");
        sb.append("![System waste heat per GPU](docs/figures/gpu_tdp_timeline.png)\n\n");
        sb.append("**Y-axis:** 100 W light bulbs running nonstop per GPU (easier than watts alone).\n\n");
        sb.append("Each generation runs **hotter on purpose** for AI speed. Forecast points (†) use public roadmap targets.\n\n");
    }

    private static void appendStoryRow(StringBuilder sb, ResultsSummary summary, ClimateAnalogies impact,
                                       String sweepId, int matchKey, String story) {
        appendStoryRow(sb, summary, impact, sweepId, matchKey, story, null);
    }

    private static void appendStoryRow(StringBuilder sb, ResultsSummary summary, ClimateAnalogies impact,
                                       String sweepId, int matchKey, String story, String profileId) {
        SweepPoint p = findPoint(summary, sweepId, matchKey, profileId);
        if (p == null) return;
        double cars = impact.carsFromAnnualTonnes(p.annualizedNetTonnes());
        sb.append(String.format(Locale.US,
                "| %s | %,d | %s | %d | %s | %s |\n",
                story, p.gpuCount(), p.profileName(), p.halls(),
                impact.formatCars(cars),
                shortMeaning(impact, p.annualizedNetTonnes())));
    }

    private static String shortMeaning(ClimateAnalogies impact, double tonnes) {
        double cars = impact.carsFromAnnualTonnes(tonnes);
        double households = tonnes / 8.5;
        return String.format(Locale.US, "Like %s parked for a year, or ~%,.0f homes' energy use",
                impact.formatCars(cars), households);
    }

    private static void appendStory(StringBuilder sb, ResultsSummary summary, ClimateAnalogies impact,
                                    String title, String sweepId, int matchKey) {
        appendStory(sb, summary, impact, title, sweepId, String.valueOf(matchKey), null);
    }

    private static void appendStory(StringBuilder sb, ResultsSummary summary, ClimateAnalogies impact,
                                    String title, String sweepId, String profileId) {
        appendStory(sb, summary, impact, title, sweepId, null, profileId);
    }

    private static void appendStory(StringBuilder sb, ResultsSummary summary, ClimateAnalogies impact,
                                    String title, String sweepId, String matchKey, String profileId) {
        SweepPoint p;
        if (profileId != null) {
            p = summary.bySweep(sweepId).stream()
                    .filter(pt -> pt.profileId().equals(profileId))
                    .findFirst().orElse(null);
        } else if (matchKey != null && matchKey.startsWith("202")) {
            p = summary.bySweep(sweepId).stream()
                    .filter(pt -> pt.label().startsWith(matchKey))
                    .findFirst().orElse(null);
        } else if (matchKey != null) {
            p = findPoint(summary, sweepId, Integer.parseInt(matchKey), null);
        } else {
            p = null;
        }
        if (p == null) return;
        sb.append("**").append(title).append("** — ");
        sb.append(impact.explainRemoval(p.annualizedNetTonnes()));
        sb.append(" Limitation: our MVP routes heat to one load at a time.\n\n");
    }

    private static void appendWorthItSection(
            StringBuilder sb, ResultsSummary summary, ClimateAnalogies impact,
            GpuProfile.GpuProfileRegistry registry
    ) throws IOException {
        OperationalCarbon ops = OperationalCarbon.fromConfig();
        sb.append("### Is it worth it? — recovery from GPU operations\n\n");
        sb.append("Comparing to \"cars off the road\" can feel underwhelming for 25,000 GPUs. "
                + "The sharper question: **how much of this hall's own GPU electricity CO₂ do we recuperate?**\n\n");
        sb.append("| Hall | Grid CO₂ from running GPUs | DAC net removes | **Recovery** | Still net emitter? |\n");
        sb.append("|------|---------------------------|-----------------|--------------|-------------------|\n");

        appendRecoveryRow(sb, summary, impact, ops, registry, "gpu_generation", "B200_LC",
                "25k B200 (reference)");
        appendRecoveryRow(sb, summary, impact, ops, registry, "gpu_generation", "H100_SXM",
                "25k H100");
        appendRecoveryRow(sb, summary, impact, ops, registry, "gpu_count_ramp", null,
                "5k H100 lab", 5000, "H100_SXM");
        appendRecoveryRow(sb, summary, impact, ops, registry, "multi_hall", null,
                "10 halls × 25k B200", 10, "B200_LC");

        sb.append("\n**How we compute \"GPU operations CO₂\":** average waste-heat power (same daily cycle as the sim) "
                + "× facility PUE 1.15 × U.S. grid 0.39 kg CO₂/kWh. Waste heat ≈ IT electricity becoming heat.\n\n");

        SweepPoint ref = summary.bySweep("gpu_generation").stream()
                .filter(p -> "B200_LC".equals(p.profileId()))
                .findFirst().orElse(null);
        if (ref != null) {
            OperationalCarbon.RecoveryAnalysis r = ops.forHall(
                    registry.require("B200_LC"), ref.gpuCount(), registry, ref.annualizedNetTonnes());
            sb.append("**Reference hall (25k B200):** ").append(ops.explainRecovery(r, impact)).append("\n\n");
            sb.append("**Bottom line:** Waste-heat DAC is a **partial clawback** of operational emissions — "
                    + "worth it as a side gig on heat you'd dump anyway, not as a license to build more GPUs for climate.\n\n");
        }
    }

    private static void appendRecoveryRow(
            StringBuilder sb, ResultsSummary summary, ClimateAnalogies impact,
            OperationalCarbon ops, GpuProfile.GpuProfileRegistry registry,
            String sweepId, String profileId, String label
    ) throws IOException {
        SweepPoint p = summary.bySweep(sweepId).stream()
                .filter(pt -> profileId == null || pt.profileId().equals(profileId))
                .findFirst().orElse(null);
        if (p == null) return;
        appendRecoveryRow(sb, summary, impact, ops, registry, sweepId, profileId, label, p.gpuCount(), p.profileId());
    }

    private static void appendRecoveryRow(
            StringBuilder sb, ResultsSummary summary, ClimateAnalogies impact,
            OperationalCarbon ops, GpuProfile.GpuProfileRegistry registry,
            String sweepId, String profileId, String label,
            int matchKey, String profileForOps
    ) throws IOException {
        SweepPoint p;
        if ("multi_hall".equals(sweepId)) {
            p = summary.bySweep(sweepId).stream().filter(pt -> pt.halls() == matchKey).findFirst().orElse(null);
        } else {
            p = summary.bySweep(sweepId).stream()
                    .filter(pt -> pt.gpuCount() == matchKey
                            && (profileId == null || pt.profileId().equals(profileId)))
                    .findFirst().orElse(null);
        }
        if (p == null) return;
        GpuProfile profile = registry.require(profileForOps != null ? profileForOps : p.profileId());
        int gpus = "multi_hall".equals(sweepId) ? p.gpuCount() * p.halls() : p.gpuCount();
        double netTonnes = p.annualizedNetTonnes();
        OperationalCarbon.RecoveryAnalysis r = ops.forHall(profile, gpus, registry, netTonnes);
        String emitter = r.netBalanceTonnes() >= 0 ? "No (net sink)" : String.format(Locale.US,
                "Yes, by %,.0f t (≈ %s)", -r.netBalanceTonnes(),
                impact.formatCars(impact.carsFromAnnualTonnes(-r.netBalanceTonnes())));
        sb.append(String.format(Locale.US,
                "| %s | %,.0f t (≈ %s) | %,.0f t (≈ %s) | **%.0f%%** | %s |\n",
                label,
                r.operationalCo2Tonnes(), impact.formatCars(impact.carsFromAnnualTonnes(r.operationalCo2Tonnes())),
                r.netRemovedTonnes(), impact.formatCars(impact.carsFromAnnualTonnes(r.netRemovedTonnes())),
                r.recoveryPercent(), emitter));
    }

    private static void appendForecastRow(StringBuilder sb, ResultsSummary summary, ClimateAnalogies impact,
                                            String year, String story) {
        SweepPoint p = summary.bySweep("forecast_timeline").stream()
                .filter(pt -> pt.label().startsWith(year))
                .findFirst()
                .orElse(null);
        if (p == null) return;
        sb.append(String.format(Locale.US,
                "| %s | %,d | %s | %d | %s | %s |\n",
                story, p.gpuCount(), p.profileName(), p.halls(),
                impact.formatCars(impact.carsFromAnnualTonnes(p.annualizedNetTonnes())),
                shortMeaning(impact, p.annualizedNetTonnes())));
    }

    private static SweepPoint findPoint(ResultsSummary summary, String sweepId, int key, String profileId) {
        return summary.bySweep(sweepId).stream()
                .filter(p -> (p.gpuCount() == key || p.halls() == key)
                        && (profileId == null || p.profileId().equals(profileId)))
                .findFirst()
                .orElse(null);
    }
}
