package com.heater.analysis;

import java.io.IOException;
import java.util.List;
import java.util.Map;

@SuppressWarnings("unchecked")
public final class TemplateExplainer {

    private static final double CARS_TONNES = 4.6;

    private TemplateExplainer() {}

    public static String explain(ResultsSummary summary, String gpuProfilesPath) throws IOException {
        GpuProfile.GpuProfileRegistry registry = GpuProfile.load(gpuProfilesPath);
        StringBuilder sb = new StringBuilder();

        sb.append("## Scalability: GPUs, heat, and CO₂\n\n");
        sb.append("*This section was auto-generated by `./gradlew generateFigures` (template fallback).*\n\n");

        sb.append("### The takeaway\n\n");
        sb.append("- **More GPUs make more waste heat** — like more engines running in a parking lot.\n");
        sb.append("- **More heat can remove more CO₂** if capture equipment scales with the GPUs (bigger bucket).\n");
        sb.append("- **Newer chips run hotter per GPU**, so the same building with next-gen silicon can do more climate work.\n\n");

        sb.append("### How many GPUs are we talking about?\n\n");
        sb.append(String.format(
                "Our reference hall uses **%,d %s GPUs** at about **%.0f MW** average waste heat "
                        + "(heat per GPU × GPU count).\n\n",
                registry.referenceGpuCount(),
                registry.referenceProfile().displayName(),
                registry.referenceProfile().avgWasteHeatMw(registry.referenceGpuCount())
        ));

        appendChartSection(sb, summary, "gpu_count_ramp", "co2_vs_gpu_count.png",
                "More GPUs (H100)", "More students → more leftover hot food → more composting",
                "Line rises when plant grows with GPU count.");
        appendChartSection(sb, summary, "gpu_generation", "co2_vs_gpu_generation.png",
                "Same 37,000 GPUs, different generations", "Same stoves, stronger burners each upgrade",
                "Newer GPUs push more heat per chip.");
        appendChartSection(sb, summary, "saturation", "co2_saturation_gpu.png",
                "Fixed plant, more heat", "Fire hose into a fixed bucket",
                "Curve flattens when capture equipment is maxed out.");
        appendChartSection(sb, summary, "multi_hall", "co2_multi_hall.png",
                "Campus rollout", "Copy one successful compost program to many schools",
                "More halls ≈ more total CO₂ removed.");
        appendGrossNetSection(sb, summary);
        sb.append("### GPU heat timeline\n\n");
        sb.append("![System waste heat per GPU](docs/figures/gpu_tdp_timeline.png)\n\n");
        sb.append("Phone-charger analogy: each generation runs **hotter on purpose** for AI speed. "
                + "Forecast points use public roadmap targets, not secret NVIDIA data.\n\n");

        sb.append("### Results table\n\n");
        sb.append("| Story | GPUs | Chip | Halls | Net CO₂e/year | So what? |\n");
        sb.append("|-------|------|------|-------|---------------|----------|\n");
        appendStoryRow(sb, summary, "gpu_count_ramp", 5000, "Lab cluster");
        appendStoryRow(sb, summary, "gpu_count_ramp", 37000, "One AI hall (H100 scale)");
        appendStoryRow(sb, summary, "multi_hall", 10, "10-hall campus");
        appendForecastRow(sb, summary, "2028", "Rubin forecast");

        sb.append("\n### Four stories\n\n");
        appendStory(sb, summary, "The lab (5k GPUs)", "gpu_count_ramp", 5000);
        appendStory(sb, summary, "The hall (37k GPUs)", "gpu_generation", null);
        appendStory(sb, summary, "The campus (10 halls)", "multi_hall", 10);
        appendStory(sb, summary, "The future (Rubin)", "forecast_timeline", 2026);

        sb.append("### Common questions (FAQ)\n\n");
        sb.append("**Does more AI automatically help the climate?** No — only if waste heat powers capture, not the sky.\n\n");
        sb.append("**Why does electricity matter?** Heat pumps need grid power, which still emits CO₂.\n\n");
        sb.append("**Why zero algae sometimes?** Our MVP routes heat to one load at a time; DAC often wins.\n\n");
        sb.append("**Is this a full climate fix?** No — meaningful for one campus, tiny vs global emissions.\n\n");
        sb.append("**Are Rubin numbers real?** Forecast from public roadmaps, not NVIDIA internal data.\n\n");

        sb.append("### Generated at: ").append(summary.generatedAt()).append("\n\n");
        sb.append("### Forecast disclaimer\n\n");
        sb.append("Forecast GPU profiles (B300, Rubin) use **public GTC and analyst targets**. "
                + "They illustrate direction, not guaranteed specs.\n");

        return sb.toString();
    }

    private static void appendChartSection(
            StringBuilder sb, ResultsSummary summary, String sweepId, String chartFile,
            String title, String analogy, String lesson
    ) {
        sb.append("### ").append(title).append("\n\n");
        sb.append("![").append(title).append("](docs/figures/").append(chartFile).append(")\n\n");
        sb.append("**Analogy:** ").append(analogy).append("\n\n");
        sb.append("**Lesson:** ").append(lesson).append("\n\n");
        List<SweepPoint> pts = summary.bySweep(sweepId);
        if (!pts.isEmpty()) {
            SweepPoint p = pts.get(pts.size() / 2);
            sb.append(String.format("**Sim highlight:** %s → **%,.0f tonnes/year** net CO₂e.\n\n",
                    p.label(), p.annualizedNetTonnes()));
        }
    }

    private static void appendGrossNetSection(StringBuilder sb, ResultsSummary summary) {
        sb.append("### Gross vs net CO₂\n\n");
        sb.append("![Gross vs net](docs/figures/gross_vs_net_co2.png)\n\n");
        sb.append("**Analogy:** Gross = cookies baked; net = cookies minus eggs you bought.\n\n");
        List<SweepPoint> pts = summary.bySweep("gpu_count_ramp");
        if (!pts.isEmpty()) {
            SweepPoint p = pts.get(pts.size() - 1);
            sb.append(String.format("At **%,d GPUs**: gross **%,.0f** vs net **%,.0f tonnes/year**.\n\n",
                    p.gpuCount(), p.annualizedGrossTonnes(), p.annualizedNetTonnes()));
        }
    }

    private static void appendStoryRow(StringBuilder sb, ResultsSummary summary,
                                       String sweepId, int matchKey, String story) {
        SweepPoint p = findPoint(summary, sweepId, matchKey);
        if (p == null) return;
        long cars = Math.round(p.annualizedNetTonnes() / CARS_TONNES);
        sb.append(String.format("| %s | %,d | %s | %d | %,.0f | ~%,d cars off the road |\n",
                story, p.gpuCount(), p.profileName(), p.halls(), p.annualizedNetTonnes(), cars));
    }

    private static void appendStory(StringBuilder sb, ResultsSummary summary,
                                    String title, String sweepId, Integer matchKey) {
        SweepPoint p = matchKey != null ? findPoint(summary, sweepId, matchKey) : findBySweep(summary, sweepId);
        if (p == null) return;
        sb.append("**").append(title).append("** — ");
        sb.append(String.format("%,d %s GPUs, %d hall(s), **%,.0f tonnes/year** net. ",
                p.gpuCount(), p.profileName(), p.halls(), p.annualizedNetTonnes()));
        sb.append("Limitation: one heat pipe at a time in this MVP.\n\n");
    }

    private static SweepPoint findPoint(ResultsSummary summary, String sweepId, int key) {
        return summary.bySweep(sweepId).stream()
                .filter(p -> p.gpuCount() == key || p.halls() == key)
                .findFirst()
                .orElse(null);
    }

    private static SweepPoint findBySweep(ResultsSummary summary, String sweepId) {
        List<SweepPoint> pts = summary.bySweep(sweepId);
        return pts.isEmpty() ? null : pts.get(pts.size() / 2);
    }

    private static void appendForecastRow(StringBuilder sb, ResultsSummary summary, String year, String story) {
        SweepPoint p = summary.bySweep("forecast_timeline").stream()
                .filter(pt -> pt.label().startsWith(year))
                .findFirst()
                .orElse(null);
        if (p == null) return;
        long cars = Math.round(p.annualizedNetTonnes() / CARS_TONNES);
        sb.append(String.format("| %s | %,d | %s | %d | %,.0f | ~%,d cars off the road |\n",
                story, p.gpuCount(), p.profileName(), p.halls(), p.annualizedNetTonnes(), cars));
    }
}
